### ISSUE TITLE
C++20 tracking issue

### ISSUE THREAD

**Issue by hebasto** [bitcoin-core/leveldb-subtree#38]
In the light of https://github.com/bitcoin/bitcoin/pull/28349, should we consider backporting of https://github.com/google/leveldb/pull/1008?

**Comment by maflcko** [comment]
I don't understand your question. Please clarify, and make sure to either add references to the C++ specification, or exact steps to reproduce.

For context, in C++20 and C++17, `= default`, or omitting it, should make no difference with regard to aggregate initialization. This is easy to see on https://godbolt.org/z/v1zW1zn65
