### ISSUE TITLE
Move SSE4 detection function out of SSE4 compiled object and upstream the result.

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin-core/leveldb-subtree#4]
In theory, the detect function could use SSE4 instructions and crash on non-SSE4 hosts; not the kind of "detection" we want. :)

**Comment by eklitzke** [comment]
It looks like they implemented more reliably detection for this in their new crc32c library, using `cpuid.h` and `nmmintrin.h`. We can just switch to that when we merge upstream changes (as in #17).

**Comment by laanwj** [comment]
This was addressed in #5 (and we're switching to the `crc32c` library soon with upstream).
